// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hkodujjfbxnqwcrhjdau.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhrb2R1ampmYnhucXdjcmhqZGF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwMTEyNTQsImV4cCI6MjA2MDU4NzI1NH0.3SnQkDbEhWyeCjp9EwHrjMlpGDXSpO03wOFvhBmsfXY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);